### ISSUE TITLE
runtime not being returned from imdb

### ISSUE THREAD

**Issue by copperhead57** [andig/videodb#198]
runtime not being returned from imdb

**Comment by johanneskonst** [comment]
I was working on a new imdb parser that pulled all info from the json blobs they put inside the pages now, but I managed to lose it :-/
Haven't been able to determine if it's a viable option across multiple movies, but r.n. there is a "runtime" "seconds" bit and a "runtime" "displayableProperty""plainText" bit that might be usefull if we want to scrape it the current-parser way.
I hope to get my dev-env for videodb back up and running sometime soon so that i can finish the parser-work i started on a long time ago :-)

**Comment by copperhead57** [comment]
@johanneskonst I started looking at json blob awhile ago. 
I have revisited it and have a version in my branch [json-blob-imdb](https://github.com/copperhead57/videodb/tree/json-blob-imdb).
happy for you to look at and give feedback
will open new issue to cover this
cheers
